services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile.api
    image: react-flask-app-api
    ports:
      - 5000:5000
    expose:
      - 5000
  ui:
    build:
      context: ./frontend
      dockerfile: Dockerfile.ui
    image: react-flask-app-ui
    ports:
      - 3000:3000
    expose:
      - 3000