
FROM python:3.9
RUN mkdir /cruddyapi
WORKDIR /cruddyapi

COPY requirements.txt users.db apiRouter.py app.py .
RUN pip install -r requirements.txt

EXPOSE 5000

CMD [ "python", "-m", "flask", "run", "--host=0.0.0.0"]